type RnmToCategoryInfo = {
    category: string,
    price_per: "KILOGRAM" | "UNIT"
    organic: boolean
}
export const rnmToCategory : {[name:string]:RnmToCategoryInfo} = {
    "POIRE Conférence France vrac": {category: "en:pears", price_per: "KILOGRAM", organic: false},
    "POIRE France biologique": {category: "en:pears", price_per: "KILOGRAM", organic: true},
    "POMME Bicolore France biologique": {category: "en:apples", price_per: "KILOGRAM", organic: true},
    "POMME Bicolore France sachet": {category: "en:apples", price_per: "KILOGRAM", organic: false}, 
    "POMME Gala France 136/180g vrac": {category: "en:gala-apples", price_per: "KILOGRAM", organic: false},
    "POMME Golden France biologique": {category: "en:golden-delicious-apples", price_per: "KILOGRAM", organic: true},
    "POMME Golden France 136/180g vrac": {category: "en:golden-delicious-apples", price_per: "KILOGRAM", organic: false},
    "RAISIN blanc Chasselas sans label France vrac": {category: "en:grapes", price_per: "KILOGRAM", organic: false},
    "RAISIN blanc France biologique": {category: "en:grapes", price_per: "KILOGRAM", organic: true},
    "CLÉMENTINE Corse cdt": {category: "en:clementines", price_per: "KILOGRAM", organic: false},
    "CLÉMENTINE France biologique": {category: "en:clementines", price_per: "KILOGRAM", organic: true},

    "CAROTTE France lavée biologique": {category: "en:carrots", price_per: "KILOGRAM", organic: true},
    "CAROTTE France lavée vrac": {category: "en:carrots", price_per: "KILOGRAM", organic: false},
    "COURGETTE longue verte France biologique": {category: "en:zucchini", price_per: "KILOGRAM", organic: true},
    "COURGETTE longue verte France vrac": {category: "en:zucchini", price_per: "KILOGRAM", organic: false},
    "CONCOMBRE France biologique (la pièce)": {category: "en:cucumbers", price_per: "UNIT", organic: true},
    "CONCOMBRE France (la pièce)": {category: "en:cucumbers", price_per: "UNIT", organic: false},
    "TOMATE ronde ou ronde grappe France biologique": {category: "en:tomatoes", price_per: "KILOGRAM", organic: true},
    "TOMATE ronde rouge France 57-67 ou 67-82mm vrac": {category: "en:tomatoes", price_per: "KILOGRAM", organic: false},
    "POIREAU France entier vrac": {category: "en:leeks", price_per: "KILOGRAM", organic: false},
    "POIREAU France entier biologique": {category: "en:leeks", price_per: "KILOGRAM", organic: true},
    "AIL blanc sec France biologique": {category: "en:garlic", price_per: "KILOGRAM", organic: true},
    "AIL blanc sec France vrac": {category: "en:garlic", price_per: "KILOGRAM", organic: false},
    "OIGNON jaune France filet 1kg": {category: "en:onions", price_per: "KILOGRAM", organic: false},
    "OIGNON jaune France biologique": {category: "en:onions", price_per: "KILOGRAM", organic: true},
    "CHOU FLEUR France (la pièce)": {category: "en:cauliflowers", price_per: "UNIT", organic: false},
    "CHOU FLEUR France biologique": {category: "en:cauliflowers", price_per: "UNIT", organic: true},
    "COURGE Potimarron France (la pièce)": {category: "en:red-kuri-squash", price_per: "UNIT", organic: false},
    "COURGE Potimarron France biologique (la pièce)": {category: "en:red-kuri-squash", price_per: "UNIT", organic: true},
    "POMME DE TERRE de conservation France vrac": {category: "en:potatoes", price_per: "KILOGRAM", organic: false},
    "POMME DE TERRE France biologique": {category: "en:potatoes", price_per: "KILOGRAM", organic: true},
    "ENDIVE France vrac": {category: "en:endives", price_per: "KILOGRAM", organic: false},
    "BANANE France vrac": {category: "en:bananas", price_per: "KILOGRAM", organic: false},
}